"""Rendering for CORPUS.md, kept in the repository on purpose.

The figures come from the measurement apparatus, which is not version
controlled and needs a corpus of cloned repositories to say anything. That
means CI cannot recompute them - but CI is exactly where a claim like "every
number here is checked" has to be enforceable, or it is a claim about the
author's memory.

So the check is split at the line where the evidence changes:

  - `CORPUS-figures.json` and `CORPUS.md` are both committed, and
    `tests/test_corpus_report.py` re-renders one from the other on every run.
    That catches a hand-edited report and a report left behind when the
    figures moved. It needs nothing but this repository.
  - `corpus_report.py --check` in the hardening tree compares the figures
    against the live sweep. That catches the corpus moving under them, and it
    can only run where the corpus is.

This module holds the rendering half so there is ONE copy of it. The generator
imports this file rather than carrying its own, because two renderers would
drift and the drift would be invisible - both would keep producing plausible
markdown.
"""
from __future__ import annotations

import textwrap

# The tiers whose precision is worth reporting. The agent corpus is excluded
# because it is 17 of 17 inside the retired design corpus, so its precision was
# never taken and would be worthless if it had been. Its COVERAGE survives,
# because tuning suppresses false positives rather than manufacturing true
# findings, and coverage is reported for it elsewhere in the report.
PRECISION_TIERS = ("bench", "heldout", "niche")


BANNER = (
    "<!-- GENERATED by corpus_report.py in the measurement tree. Do not edit by "
    "hand: every number here is rendered from CORPUS-figures.json beside it, "
    "and tests/test_corpus_report.py fails if the two disagree. See the last "
    "section for what that does and does not guarantee. -->"
)


def _n(value) -> str:
    """Thousands separators, and a visible marker when a figure is absent.

    An absent number must never render as an empty gap, which reads as prose
    and hides that nothing was measured.
    """
    if value is None:
        return "NOT MEASURED"
    return f"{value:,}" if isinstance(value, int) else str(value)


def _rewrap(lines: list[str]) -> list[str]:
    """Re-wrap prose paragraphs, leaving structure alone.

    The prose is assembled with figures interpolated into it, so the line
    lengths are not known when it is written and hand-wrapping produces a
    ragged file that changes shape whenever a number gains a digit. Wrapping
    here instead makes the output depend only on the TEXT, which is what makes
    a `--check` diff readable: a changed figure moves the words around it and
    nothing else.

    Tables, headings, fences and the HTML banner keep their exact bytes.
    """
    out: list[str] = []
    para: list[str] = []
    in_fence = False

    def wrap(text: str) -> list[str]:
        """Wrap, then refuse any width that starts a line with a list marker.

        This prose uses " - " where an em-dash would go, because the repository
        is ASCII only. Wrap it at the wrong width and a continuation line
        begins "- 5 of 50 repositories...", which markdown renders as a bullet
        in the middle of a paragraph. The text is correct and the document is
        wrong, which is the worst kind of defect to have in a generated file:
        nothing is inconsistent, so no check fires.

        Narrowing by a column shifts the break and is invisible in the output,
        so it is preferred to rewording. If no width in the range works the
        widest is returned rather than looping forever - a slightly odd
        paragraph beats a generator that hangs.
        """
        for width in range(79, 69, -1):
            lines = textwrap.wrap(text, width=width, break_long_words=False,
                                  break_on_hyphens=False)
            if not any(ln.startswith(("- ", "* ", "+ ")) for ln in lines[1:]):
                return lines
        return textwrap.wrap(text, width=79, break_long_words=False,
                             break_on_hyphens=False)

    def flush() -> None:
        if para:
            out.extend(wrap(" ".join(para)))
            para.clear()

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("```"):
            flush()
            in_fence = not in_fence
            out.append(line)
            continue
        if in_fence or not stripped:
            flush()
            out.append(line)
            continue
        if stripped.startswith(("#", "|", "<!--", "- ", "* ")):
            flush()
            out.append(line)
            continue
        para.append(stripped)
    flush()
    return out


def render(fig: dict) -> str:
    c, h, prov = fig["corpus"], fig["holdout"], fig["provenance"]
    census, pilot = fig["sha_census"], fig["agent_pilot"]
    bench = c["per_tier"]["bench"]
    L: list[str] = [BANNER, "", "# What extant finds, measured", ""]

    L += [
        "extant checks whether the claims in a project's documentation are still",
        "true, against git and the filesystem. It never judges whether a value is",
        "CORRECT, only whether something the documentation names still exists or",
        "still holds: a commit that no longer resolves, a file a link points at, a",
        "heading an anchor expects, a version claimed as released with no such tag.",
        "A `finding` below is one such claim that no longer holds. Numbers and",
        "dates are deliberately out of scope, because nothing can check them.",
        "",
        "This is what that finds when it is pointed at other people's",
        "repositories. Every figure is computed from recorded sweeps rather than",
        "from a demonstration, and none of it is typed by hand: the report is",
        "rendered from the measurements, so a stale number fails a check instead",
        "of surviving in prose. The last section says exactly which check runs",
        "where, and what is still left to human discipline.",
        "",
        "## The corpora",
        "",
        "| corpus | repositories | documents | findings | ordinary | reporting |",
        "|:---|---:|---:|---:|---:|---:|",
    ]
    for tier in ("bench", "heldout", "niche", "agent"):
        t = c["per_tier"].get(tier, {})
        if "unavailable" in t:
            continue
        L.append(
            f"| {tier} | {_n(t['repositories'])} | {_n(t['documents'])} | "
            f"{_n(t['findings'])} | {_n(t['ordinary_findings'])} "
            f"({t['ordinary_share']}%) | {_n(t['repos_reporting_ordinary'])} |")
    L += [
        "",
        f"Counted over the swept population, which is the same population the",
        f"precision figures use. Across all four that is "
        f"{_n(c['distinct_repositories'])} distinct repositories; the tiers",
        f"share {_n(c['shared_across_tiers'])}, so the rows above do not simply",
        f"add up.",
        "",
        "`ordinary` is what is left once the strata separate out changelogs,",
        "vendored trees, generated API references and per-release documentation",
        "snapshots. It is the half a reader would act on, and on the benchmark",
        "it is a small fraction of the total:",
        "",
        "| stratum | findings |",
        "|:---|---:|",
    ]
    for stratum, n in sorted(bench["strata"].items(), key=lambda kv: -kv[1]):
        L.append(f"| {stratum} | {_n(n)} |")
    L += [
        "",
        f"So {_n(bench['findings'] - bench['ordinary_findings'])} of "
        f"{_n(bench['findings'])} benchmark findings sit in a kind of tree",
        f"nobody would act on. They are labelled rather than hidden, and the",
        f"ordinary count is what the summary leads with.",
        "",
    ]
    conc = bench.get("ordinary_concentration")
    if conc:
        L += [
            f"Concentration is reported rather than left to be discovered: the",
            f"largest single contributor to the benchmark's ordinary findings is",
            f"`{conc['largest_repository']}`, at {_n(conc['findings'])} of them",
            f"({conc['share_pct']}%).",
            "",
        ]

    L += [
        "## The reserve",
        "",
        f"**{_n(h['never_swept_total'])} repositories have never been swept.**",
        f"They are held back so a rule change can be measured against ground it",
        f"was not tuned on, and opening them requires a stated reason that is",
        f"printed with the results.",
        "",
        "| corpus | in manifest | reserved | swept | never swept |",
        "|:---|---:|---:|---:|---:|",
    ]
    for tier, t in sorted(h["tiers"].items()):
        L.append(f"| {tier} | {_n(t['manifest'])} | {_n(t['reserved'])} | "
                 f"{_n(t['swept'])} | {_n(t['never_swept'])} |")
    L += [
        "",
        f"Two different things wear the word. {_n(h['reserved_but_swept'])}",
        f"benchmark repositories are flagged reserve but were swept, and are",
        f"only withheld from tuning decisions. Just the",
        f"{_n(h['never_swept_total'])} never-swept ones can answer whether a",
        f"rule fires on ground nobody has looked at, so they are counted apart",
        f"instead of summed.",
        "",
    ]
    if h["unexplained_absences"]:
        L += ["Absent for some other reason: "
              + ", ".join(h["unexplained_absences"]) + ".", ""]

    policies = bench.get("policies")
    if policies:
        inst, ordinary_pol = policies.get("installed"), policies.get("ordinary")
        L += ["## What a default install actually checks", ""]
        if inst and ordinary_pol and ordinary_pol["gated"]:
            # ORDINARY on both sides. Comparing `installed`'s all-strata count
            # to an ordinary-only denominator mixes two populations in the
            # report's most quotable sentence, which is the exact defect the
            # denominators exist to expose. The all-strata pair is given after
            # it so neither number has to be looked up.
            L += [
                f"A survey of the whole repository is not what an adopter gets. "
                f"The installer configures the one or two documents it can name "
                f"with confidence, and on the benchmark that gate covers "
                f"**{_n(inst['ordinary'])} of the {_n(ordinary_pol['ordinary'])} "
                f"ordinary findings** the survey sees - "
                f"{_n(inst['repos'])} of {_n(bench['repositories'])} "
                f"repositories report anything at all under it. The rest would "
                f"exit 0 forever, which is a validator teaching its adopters it "
                f"has nothing to say.",
                "",
                f"Counted across every stratum rather than ordinary alone it is "
                f"{_n(inst['gated'])} of {_n(bench['findings'])}, which is the "
                f"same story told about a larger pile.",
                "",
                "The cause is document SELECTION rather than the rules, so the "
                "fix is a wider document set. Each policy below was measured "
                "over the same sweep; `pinned paths` is the standing liability "
                "each one accepts, because a pinned document that later moves "
                "becomes a finding until somebody edits the config:",
                "",
                "| policy | findings gated | ordinary | paths pinned | "
                "repositories reporting |",
                "|:---|---:|---:|---:|---:|",
            ]
            ladder = ("installed", "root", "root+docs", "root+docs-ord",
                      "docs2-ord", "docs3-ord", "docs4-ord", "ordinary")
            for name in ladder:
                v = policies.get(name)
                if not v:
                    continue
                L.append(f"| `{name}` | {_n(v['gated'])} | {_n(v['ordinary'])} "
                         f"| {_n(v['pinned_paths'])} | {_n(v['repos'])} |")
            # Both comparisons below are computed, because both are the kind of
            # claim that reads as rhetoric unless the arithmetic is on the page.
            def per_path(name: str) -> float:
                v = policies[name]
                return v["ordinary"] / v["pinned_paths"] if v["pinned_paths"] else 0.0

            L += ["", "Two of those rows are worth reading against each other."]
            if policies.get("root") and inst["pinned_paths"]:
                L += [
                    f"`root` gates {_n(policies['root']['gated'])} findings "
                    f"against `installed`'s {_n(inst['gated'])} and is still "
                    f"the worse policy: per path it pins, it returns "
                    f"{per_path('root'):.3f} ordinary findings against "
                    f"{per_path('installed'):.3f}. Most of what it collects is "
                    f"`CHANGELOG.md`, which is why every widened policy here is "
                    f"restricted to the ordinary stratum - the restriction is "
                    f"the feature rather than a refinement of it.",
                ]
            if policies.get("docs3-ord") and policies.get("docs4-ord"):
                d3, d4 = policies["docs3-ord"], policies["docs4-ord"]
                L += [
                    "",
                    f"And a fourth level is a cliff rather than a slope: "
                    f"{_n(d4['gated'] - d3['gated'])} more findings for "
                    f"{_n(d4['pinned_paths'] - d3['pinned_paths'])} more pinned "
                    f"paths. That is where the default depth stops.",
                ]
            L += [""]

        # `installed` cannot be measured where no config was ever written, and
        # that is not the same as gating nothing. Reported, because a zero in
        # this table would otherwise read as a measurement.
        unmeasured = []
        for tier in ("heldout", "niche", "agent"):
            t = c["per_tier"].get(tier, {})
            pol = (t.get("policies") or {}).get("installed")
            if pol and pol.get("no_answer"):
                unmeasured.append(f"{tier} ({_n(pol['no_answer'])} of "
                                  f"{_n(t['repositories'])})")
        if inst and inst.get("no_answer"):
            unmeasured.insert(0, f"bench ({_n(inst['no_answer'])} of "
                                 f"{_n(bench['repositories'])})")
        if unmeasured:
            L += [
                "The `installed` row counts only the repositories the installer "
                "agreed to configure. Everywhere it refused to write a "
                "configuration at all, the policy has no answer rather than an "
                "answer of zero: "
                + "; ".join(unmeasured) +
                ". Those repositories were never asked the question, which is a "
                "different thing from being asked and reporting nothing, and "
                "folding them in as zeroes would understate the gate while "
                "looking like a measurement.",
                "",
            ]

    L += ["## Precision", ""]
    bp = fig["precision"].get("bench", {}).get("pooled")
    if bp and bp.get("raw_pct") is not None:
        L += [
            f"Against a hand-labelled sample of {_n(bp['n'])} findings, pooled",
            f"precision is **{bp['raw_pct']}%** raw and "
            f"{bp['reweighted_pct']}% reweighted by stratum.",
            "",
        ]
    L += [
        "Precision of exactly the findings a wider gate would newly FAIL a build",
        "on is measured separately, because the cost of being wrong changes",
        "character once a survey line becomes a failing build. Each row names the",
        "selection policy it was measured under; they are not interchangeable.",
        "",
        "| corpus | policy | judged | resolve under some reading | precision |",
        "|:---|:---|---:|---:|---:|",
    ]
    for tier in PRECISION_TIERS:
        gated = fig["precision"].get(tier, {}).get("gated", {})
        for policy, g in sorted(gated.items()):
            L.append(f"| {tier} | `{policy}` | {_n(g['judged'])} | "
                     f"{_n(g['resolve_under_some_reading'])} | "
                     f"{g['precision_pct']}% |")
    L += [
        "",
        "A finding counts against precision if its citation resolves under ANY",
        "reading a real one could legitimately have: case-folded, a missing",
        "extension, a directory index, a schemeless URL. That is deliberately",
        "harsher than re-running the rule, which would re-ask the rule's own",
        "question and agree with itself.",
        "",
        "## SHA citations, and the answer that inverted the question",
        "",
        f"This section counts a DIFFERENT set of repositories from the tables",
        f"above, and the difference is not an error: asking git whether a cited",
        f"commit exists needs full history, so it was run over the corpora that",
        f"were cloned with it rather than over the shallow ones. That is",
        f"{_n(census['distinct_repositories'])} distinct repositories from",
        f"{_n(census['clone_rows'])} clones, {_n(census['duplicated_repositories'])}",
        f"of them held twice and de-duplicated in favour of the deeper copy.",
        "",
        f"Across those, documentation cites {_n(census['citations'])} commit",
        f"SHAs, {_n(census['distinct_tokens'])} of them distinct.",
        "",
        "| what git says | citations |",
        "|:---|---:|",
    ]
    for verdict, n in sorted(census["verdicts"].items(), key=lambda kv: -kv[1]):
        L.append(f"| {verdict} | {_n(n)} |")
    L += [
        "",
        f"{census['absent_pct']}% of cited SHAs do not resolve, and the obvious",
        f"reading is that documentation invents them. Asked properly on a",
        f"held-out agent-written project, it answered the other way: every dead",
        f"SHA there appeared in the rewrite map a history rewrite had left",
        f"behind. They were not invented, they were rewritten, and the evidence",
        f"was on disk the whole time. A further {_n(census['hex_collision'])}",
        f"are hex collisions that were never commit citations at all.",
        "",
        "## The agent pilot that decided nothing",
        "",
        f"A pilot asked whether an agent given a validator verifies claims more",
        f"reliably than one without: {_n(pilot['sessions'])} sessions across",
        f"{_n(len(pilot['arms']))} arms, {_n(pilot['planted_defects'])} planted",
        f"defects each.",
        "",
        "| arm | sessions | detected | false negatives | false alarms |",
        "|:---|---:|:---|:---|:---|",
    ]
    for arm, a in pilot["arms"].items():
        L.append(f"| {arm} | {_n(a['sessions'])} | "
                 f"{', '.join(str(d) for d in a['detected'])} | "
                 f"{', '.join(str(d) for d in a['false_negatives'])} | "
                 f"{', '.join(str(d) for d in a['false_alarms'])} |")
    if pilot["saturated"]:
        L += [
            "",
            f"**Every arm detected {pilot['every_arm_detected']} of",
            f"{pilot['planted_defects']}, with no false negatives anywhere.**",
            f"That is not a finding that the arms are equal - it is a fixture",
            f"that cannot tell them apart. The pilot is reported as saturated",
            f"and deciding nothing, because publishing the scores without that",
            f"sentence would read as a result about agents.",
            "",
        ]

    L += ["## What changed since these figures were first published", ""]
    if "removed_since_stage4" in prov:
        r = prov["removed_since_stage4"]
        L += [
            f"An earlier write-up recorded",
            f"{_n(prov['stage4_frozen']['findings'])} benchmark findings",
            f"({_n(prov['stage4_frozen']['ordinary'])} ordinary). The current",
            f"figure is {_n(prov['live']['findings'])}",
            f"({_n(prov['live']['ordinary'])}). The whole difference is",
            f"{_n(r['findings'])} findings removed by one narrowing: a schemeless",
            f"URL such as `www.example.com/x` was being read as a relative path",
            f"and reported as a dead link.",
            "",
            "| corpus | before | after | removed | added |",
            "|:---|---:|---:|---:|---:|",
        ]
        for tier, n in sorted(prov["schemeless_narrowing"].items()):
            L.append(f"| {tier} | {_n(n['before'])} | {_n(n['after'])} | "
                     f"{_n(n['removed'])} | {_n(n['added'])} |")
        added = sum(n["added"] for n in prov["schemeless_narrowing"].values())
        L += [
            "",
            f"`added` is a set difference rather than a subtraction of totals, so",
            f"it would show a narrowing that removed real findings and invented",
            f"new ones. It reports {_n(added)}.",
            "",
        ]

    L += [
        "## How this file is kept honest",
        "",
        "It is generated, not written. The figures are computed from recorded",
        "sweeps, and the prose above is rendered from them, so a number cannot",
        "be edited here without the render stopping to match.",
        "",
        "Checking that splits in two, because the evidence for each half lives",
        "somewhere different:",
        "",
        "| what could go wrong | what catches it | where it runs |",
        "|:---|:---|:---|",
        "| this file edited by hand, or left behind when the figures moved | "
        "`tests/test_corpus_report.py` re-renders `CORPUS-figures.json` and "
        "requires it to reproduce this file | every test run, including CI |",
        "| the figures no longer match the corpus they came from | "
        "`corpus_report.py --check` | only where the corpus is, which is far "
        "too large to commit |",
        "",
        "```sh",
        "python -m pytest tests/test_corpus_report.py  # the committed pair agree",
        "python corpus_report.py --check CORPUS.md     # figures match the corpus",
        "python corpus_report.py --write CORPUS.md     # rewrite both files",
        "```",
        "",
        "Neither half is sufficient alone, and the second cannot run in CI. That",
        "is a weaker guarantee than a single check would be; it is the strongest",
        "one available without committing the corpus, and saying which half runs",
        "where seemed better than implying both always do.",
        "",
        "The generator reads only recorded measurement output. It never sweeps,",
        "clones, or asks git anything, so a figure that is not in the data",
        "cannot appear here.",
    ]
    return "\n".join(_rewrap(L)).rstrip() + "\n"
