"""CORPUS.md says every number in it is computed. This is what enforces it.

The report is generated by `corpus_report.py` in the measurement tree, which is
not version controlled and needs a corpus of cloned repositories to compute
anything. So CI cannot recompute the figures - but "every number here is
checked" is a claim about this repository, and a claim nothing enforces is a
claim about whoever wrote it.

The check is therefore split at the line where the evidence changes:

  - here, over the two committed files: re-render `CORPUS-figures.json` and
    require it to reproduce `CORPUS.md` byte for byte. That catches a report
    edited by hand and a report left behind when the figures moved, and it
    needs nothing but this repository.
  - `corpus_report.py --check` in the measurement tree, which compares those
    figures against the live sweep. That catches the corpus moving underneath
    them, and it can only run where the corpus is.

Neither half is sufficient and the report says so. What this half buys is that
the half CI can run, CI does run - on every pull request, with no new job.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from corpus_render import render

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "CORPUS.md"
FIGURES = ROOT / "CORPUS-figures.json"


def test_the_report_and_its_figures_are_both_present() -> None:
    """Either alone is a check with nothing to check against.

    A report without figures cannot be verified and a figures file without a
    report is a measurement nobody published; both look like a tidy repository
    from the outside.
    """
    assert REPORT.is_file(), f"{REPORT.name} is missing"
    assert FIGURES.is_file(), (
        f"{FIGURES.name} is missing, so {REPORT.name} cannot be checked "
        f"against anything. Regenerate both with corpus_report.py --write.")


def test_the_report_is_what_its_figures_render_to() -> None:
    """The load-bearing one: the prose cannot drift from the numbers.

    Failing here means one of two things and the diff says which - either
    CORPUS.md was edited by hand, or the figures were regenerated and the
    report was not. Both are fixed the same way, by rerunning the generator.
    """
    figures = json.loads(FIGURES.read_text(encoding="utf-8"))
    expected = render(figures)
    actual = REPORT.read_text(encoding="utf-8")

    if actual != expected:
        exp, act = expected.splitlines(), actual.splitlines()
        for i, (e, a) in enumerate(zip(act, exp), start=1):
            if e != a:
                pytest.fail(
                    f"{REPORT.name} does not match {FIGURES.name} at line {i}\n"
                    f"  committed:  {e}\n"
                    f"  renders to: {a}\n"
                    f"Rerun: python corpus_report.py --write CORPUS.md")
        pytest.fail(
            f"{REPORT.name} has {len(act)} lines, {FIGURES.name} renders to "
            f"{len(exp)}. Rerun: python corpus_report.py --write CORPUS.md")


def test_the_report_is_ascii() -> None:
    """The same rule the rest of the repository follows, for the same reason:
    a non-ASCII byte raises UnicodeEncodeError on a cp437 console."""
    raw = REPORT.read_bytes()
    bad = [i for i, byte in enumerate(raw) if byte > 127]
    assert not bad, f"{REPORT.name} has non-ASCII bytes at {bad[:5]}"


def test_a_changed_figure_changes_the_report() -> None:
    """The guard, exercised on the thing it actually guards.

    An earlier version of this test rendered the report, ran `str.replace` on
    the result, and asserted the result differed from the file. That proves
    `str.replace` works. It would have passed if `render` returned a constant,
    which is the one failure that would make every other test here vacuous.

    So the tamper is applied to the FIGURES, and the assertion is that it
    reaches the rendered output - which is the property the whole scheme rests
    on: a number cannot move in the data without moving in the document.
    """
    figures = json.loads(FIGURES.read_text(encoding="utf-8"))
    baseline = render(figures)
    assert baseline == REPORT.read_text(encoding="utf-8")

    figures["corpus"]["per_tier"]["bench"]["findings"] += 1
    assert render(figures) != baseline, (
        "changing a figure did not change the rendered report, so the "
        "comparison in the test above cannot detect a stale document")


def test_every_committed_figure_is_reachable_from_the_report() -> None:
    """A figure nobody renders is a number with no reader.

    Not every entry in the figures file appears in the report - `slugs` is
    working data - but the headline counts must, or the check above is
    guarding a document that quietly stopped mentioning them.
    """
    figures = json.loads(FIGURES.read_text(encoding="utf-8"))
    body = render(figures)
    bench = figures["corpus"]["per_tier"]["bench"]
    for label, value in (
        ("bench findings", bench["findings"]),
        ("bench ordinary findings", bench["ordinary_findings"]),
        ("never-swept reserve", figures["holdout"]["never_swept_total"]),
        ("SHA citations", figures["sha_census"]["citations"]),
    ):
        assert f"{value:,}" in body, (
            f"{label} ({value:,}) is in the figures but does not appear in the "
            f"report, so nothing would notice if it changed")
