"""What kind of document a finding came from.

Measured on 50 pinned public repositories: a sweep prints 54,790 findings and
4,431 of them are in ordinary documents. The other 92 per cent are in trees a
reader would not call documentation-with-claims - per-release snapshots,
changelogs, machine-written allowlists, vendored code and generated API
references.

`exclude_paths` already exists and does not close that gap. Three
configuration passes over the same corpus moved the headline by under one per
cent, and `install.py` refuses 35 of the 50 repositories unaided. Whether a
tree is vendored or a per-release snapshot is visible FROM THE REPOSITORY, so
it should not have to be configured.

LABELS, NOT EXCLUSIONS. Excluding hides; a stratum labels. A rule that goes
quiet because a tree was excluded is indistinguishable from a rule that broke,
which is the ambiguity the denominator exists to remove. Both mechanisms stay
and they answer different questions.

This module imports nothing from the package - it takes a string and returns a
string - so it cannot be half of an import cycle, and no rule needs to know it
exists.
"""
from __future__ import annotations

import re

__all__ = ["ORDER", "classify"]

# Precedence. First match wins, which is what makes the strata a PARTITION
# rather than overlapping buckets that sum to more than the total: bazel's
# `docs/versions/8.6.0/reference/` is generated AND snapshotted, and a fixed
# order is the only thing that stops it being counted twice.
ORDER = ("vendored", "version-snapshot", "generated", "historical-record",
         "ordinary")

# Somebody else's code, checked in. Counting findings here reports the state of
# another project through this one. 4,175 findings on the measured corpus.
_VENDORED = re.compile(
    r"(^|/)(node_modules|vendor|third_party|thirdparty|\.venv|venv|"
    r"site-packages|bower_components|external|deps|Godeps|_vendor|vendored)"
    r"(/|$)", re.IGNORECASE)

# Documentation kept as one directory per release. `bazelbuild/bazel` holds 12
# such directories, each a copy of the same tree, so one dead link written once
# is counted twelve times - 39,698 findings, 72.5 per cent of the corpus total.
_VERSION_SNAPSHOT = re.compile(
    r"(^|/)(?:versioned_docs/version-[^/]+|versions?/v?\d+[\w.]*|"
    r"v\d+(?:\.\d+)*)(/|$)", re.IGNORECASE)

# Machine-written documentation. Whether extant SHOULD flag it is a real
# question; it gets its own label rather than being folded into the headline.
_GENERATED_PATH = re.compile(
    r"(^|/)(api|apis|reference|generated|_generated|autogen|autogenerated|"
    r"_build|_site|dist|build)(/|$)", re.IGNORECASE)

# A HISTORICAL RECORD IS NOT A LIVE CLAIM. A changelog entry naming a file that
# has since moved is an accurate record of what was true at that release, not a
# claim that rotted. `angular/packages/zone.js/CHANGELOG.md` supplies 391
# findings alone and four of node's `doc/changelogs/CHANGELOG_V*.md` supply 468
# between them. An allowlist is a machine-maintained list of test-case paths in
# an EXTERNAL suite and was never a document link at all: babel's two supply
# 343.
_HISTORICAL = re.compile(
    r"(^|/)(CHANGELOG|CHANGES|HISTORY|NEWS|RELEASES?|RELEASE[-_]NOTES|"
    r"[\w.-]*allowlist|[\w.-]*denylist|[\w.-]*blocklist|[\w.-]*whitelist)"
    r"[\w.-]*\.(md|mdx)$", re.IGNORECASE)


def classify(path: str) -> str:
    """Which stratum this document belongs to. Exactly one, always.

    PATH ONLY, and the alternative is priced rather than guessed at. Reading
    each document for a do-not-edit marker would move 503 further findings
    from `ordinary` to `generated` - 11 per cent of that stratum, in 71
    documents, measured on the corpus. It is not done here because the text is
    not in scope at the call sites, and it is recorded because a deferral
    without its number is indistinguishable from an oversight.
    """
    if _VENDORED.search(path):
        return "vendored"
    if _VERSION_SNAPSHOT.search(path):
        return "version-snapshot"
    if _GENERATED_PATH.search(path):
        return "generated"
    if _HISTORICAL.search(path):
        return "historical-record"
    return "ordinary"
